mysite/frutalibre/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/frutaui/urls.py
from django.conf.urls import url

from . import views

app_name = 'frutaui'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^more$', views.more, name='more'),
    # url(r'^todavia$', views.index, name='index'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^frutalibre/', include('frutalibre.urls')),
    url(r'^', include('frutaui.urls')),
    # url(r'^frutaui/', include('frutaui.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

mysite/frutalibre/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

import pytz


# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
class Profile(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.CharField(max_length=100, blank=True)
    # locationOriginal = models.CharField(max_length=500, blank=True)
    # locationNow = models.CharField(max_length=500, blank=True)
    locationOriginal = models.ForeignKey('Location', related_name='location_original', on_delete=models.PROTECT)
    locationNow = models.ForeignKey('Location', related_name='location_now', on_delete=models.PROTECT)

    fruits = models.ManyToManyField('Fruit')

    fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        # return "{0}".format(self.user.name)
        return "{0}".format(self.email)


### Signals puestas aqui mismo
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()
###


class Fruit(models.Model):
    name = models.CharField(max_length=100)

    seasonDescription = models.CharField(max_length=500)
    idealEnvironment = models.CharField(max_length=500)

    fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        return "{0}".format(self.name)


class State(models.Model):
    name = models.CharField(max_length=50)

    fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        return "{0}".format(self.name)


class Location(models.Model): # This was a BAD name!!! Because we are using legit locations (lat lng) in newer models!
    name = models.CharField(max_length=100)
    state = models.ForeignKey(State, on_delete=models.PROTECT)

    fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        return "{0}, {1}".format(self.name, self.state.name)


class MapPin(models.Model):
    lat = models.DecimalField('Latitude', max_digits=9, decimal_places=6)
    lng = models.DecimalField('Longitude', max_digits=9, decimal_places=6)

    # in case other...

    fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        return "{0}".format(self.name)


class FruitSnap(MapPin): # snap = event = location + time
    ACCESSIBILITY = (
        ('E', 'Easy'),
        ('R', 'Regular'),
        ('C', 'Complicated'),
    )
    STARS = (
        (0, ''),
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    )

    fruit = models.ForeignKey(Fruit, on_delete=models.PROTECT)
    time = models.DateTimeField()

    imageUrl = models.CharField(max_length=300)

    accesibility = models.CharField(max_length=2, choices=ACCESSIBILITY)
    quality = models.PositiveSmallIntegerField(choices=STARS)

    # fieldvalue_tags = models.CharField('Field:Value tags', help_text="(Field1:\"Value1\")(Field2:\"Value2\")  eg.: (Color:\"Rojo\")(Carro:{Marca:\"Toyota\", Modelo:\"Rav4\", Año:2017})(Opciones:[1, 3, 5])", max_length=1000, blank=True) # TODO Add all relevant info here to see how to model in the future...

    def __str__(self):
        pr_time = self.time.astimezone(pytz.timezone('America/Puerto_Rico'))
        return "{0} ({1})".format(self.fruit.name, pr_time.strftime('%a. %m.%d %-I:%M%p'))

mysite/frutaui/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/frutalibre/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world!!!")

mysite/frutaui/views.py
from django.http import HttpResponse
from django.shortcuts import render

from frutalibre.models import FruitSnap


def index(request):
    fruits = FruitSnap.objects.all()
    context = {
        'fruits': fruits,
    }
    return render(request, 'frutaui/index.html', context)    


def more(request):
    return HttpResponse("Coming soon...")

mysite/polls/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hola corillo Fruta Libre!!!")

mysite/frutaui/templates/frutaui/base.html
<!DOCTYPE html>
<html>

<head>
    <title>FRUTA Libre{% block headTitle %}{% endblock headTitle %}</title>

    {% load static %}

    <!-- moved the following to be available from base... -->
    <link rel="stylesheet" type="text/css" href="{% static 'frutaui/style.css' %}" />

    <!-- copied the following to be available from base... -->
    <!--<script src="{% static 'sw2webui/js/jquery-3.2.0.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'sw2webui/js/jquery-ui-1.12.1/jquery-ui.css' %}" />
    <script src="{% static 'sw2webui/js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>-->

    {% block headScript %}{% endblock headScript %}

</head>

<body>

    {% block body %}{% endblock body %}

</body>

</html>

mysite/frutaui/templates/frutaui/index.html
{% extends "frutaui/base.html" %}

{% load static %}

{% block headScript %}

<!-- LEAFLET -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>

{% endblock headScript %}

{% block body %}

<!-- http://bl.ocks.org/d3noob/7654694 -->
<div id="map"></div>

    <script>
        var map = L.map('map').setView([18.25, -66.40], 8);
        mapLink = 
            '<a href="http://openstreetmap.org">OpenStreetMap</a>';
        L.tileLayer(
            'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; ' + mapLink + ' Contributors',
            maxZoom: 18,
            }).addTo(map);

{% if fruits %}

    {% for fruitsnap in fruits %}
        L.marker([{{ fruitsnap.lat }}, {{ fruitsnap.lng }}])
                    .bindPopup(`
                    <div id=\"popup\">
                    <div class=\"logo\">
                    FRUTA Libre<br><img style=\"border: 0;\" src=\"{% static 'frutaui/LOGO.png' %}\" class=\"logo\">
                    </div>
                    <br><br>
                    <a href=\"{{ fruitsnap.imageUrl }}\"><img style=\"border: 0;\" src=\"{{ fruitsnap.imageUrl }}\" class=\"fruitsnap\"></a>
                    <br>
                    <div class=\"losheaders\"><b>{{ fruitsnap.fruit.name }}</b>
                    <br>({{ fruitsnap.time|date:"Y-m-d, P" }})
                    <br><div class=\"coordinates\">(lat:{{ fruitsnap.lat|floatformat:4 }}, lng:{{ fruitsnap.lng|floatformat:4 }})</div>
                    </div>
                    <br>
                    Calidad: {{ fruitsnap.get_quality_display }}
                    <br>
                    Temporada: {{ fruitsnap.fruit.seasonDescription|truncatechars:60 }}
                    </div>
                    `, {
                    maxWidth : 150})
                    .addTo(map);
    {% endfor %}

{% else %}
{% endif %}

        // arr = [
        //     [18.25, -66.44],
        //     [18.26, -66.43],
        //     [18.27, -66.42],
        //     [18.28, -66.41],
        // ];

        // for (var i = 0, len = arr.length; i < len; i++) {
        //     // someFn(arr[i]);
        //     L.marker(arr[i])
        //         .bindPopup("<b>Hello world!</b><br>I am a popup.")
        //         .addTo(map);
        // }

        // var marker = L.marker([18.25, -66.40]).addTo(map);
        // marker.bindPopup("<b>Hello world!</b><br>I am a popup."); //.openPopup();

        // var marker = L.marker([18.26, -66.41]).addTo(map);
        // marker.bindPopup("<b>Hello world!</b><br>I am a popup2."); //.openPopup();

    </script>

{% endblock body %}